"""Fix employee skills relationships ver2

Revision ID: 3957d3e4de51
Revises: 619c87e68fde
Create Date: 2025-09-19 23:52:30.803816

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3957d3e4de51'
down_revision: Union[str, Sequence[str], None] = '619c87e68fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_skills', 'employee_id',
               existing_type=sa.BIGINT(),
               comment='Id of the employee',
               existing_nullable=False)
    op.alter_column('employee_skills', 'skill_id',
               existing_type=sa.BIGINT(),
               comment='Id of the skill',
               existing_nullable=False)
    op.drop_index('ix_employee_skills_id', table_name='employee_skills')
    op.drop_column('employee_skills', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_skills', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='Unique identifier of the employee skill'))
    op.create_index('ix_employee_skills_id', 'employee_skills', ['id'], unique=False)
    op.alter_column('employee_skills', 'skill_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Id of the skill',
               existing_nullable=False)
    op.alter_column('employee_skills', 'employee_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Id of the employee',
               existing_nullable=False)
    # ### end Alembic commands ###
