"""Fix employee skills relationships

Revision ID: 619c87e68fde
Revises: 4e7d3dfeebd4
Create Date: 2025-09-19 23:46:06.789247

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '619c87e68fde'
down_revision: Union[str, Sequence[str], None] = '4e7d3dfeebd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_skills_skill_id_fkey', 'employee_skills', type_='foreignkey')
    op.drop_constraint('employee_skills_employee_id_fkey', 'employee_skills', type_='foreignkey')
    op.create_foreign_key(None, 'employee_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employee_skills', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_skills', type_='foreignkey')
    op.drop_constraint(None, 'employee_skills', type_='foreignkey')
    op.create_foreign_key('employee_skills_employee_id_fkey', 'employee_skills', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key('employee_skills_skill_id_fkey', 'employee_skills', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###
