"""Remove Quest_Required_Actions and Quest_Action_Progress

Revision ID: 3687b4441c19
Revises: f2c8b85115fb
Create Date: 2025-09-20 11:10:08.408608

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3687b4441c19'
down_revision: Union[str, Sequence[str], None] = 'f2c8b85115fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_required_actions')
    op.drop_table('quest_action_progress')
    op.add_column('employee_quests', sa.Column('current_count', sa.Integer(), nullable=False, comment='Current progress count for the quest action'))
    op.add_column('quests', sa.Column('action_type', sa.String(length=50), nullable=False))
    op.add_column('quests', sa.Column('required_count', sa.Integer(), nullable=False))
    op.alter_column('quests', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Detailed description of the quest objectives')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quests', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Detailed description of the quest objectives')
    op.drop_column('quests', 'required_count')
    op.drop_column('quests', 'action_type')
    op.drop_column('employee_quests', 'current_count')
    op.create_table('quest_action_progress',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('employee_quest_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_quest_id'], ['employee_quests.id'], name='quest_action_progress_employee_quest_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quest_action_progress_pkey')
    )
    op.create_table('quest_required_actions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('quest_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('required_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name='quest_required_actions_quest_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quest_required_actions_pkey')
    )
    # ### end Alembic commands ###
